# Generated by Django 4.0.4 on 2022-07-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('WA', 'WATER'), ('GR', 'GRASS'), ('GH', 'GHOST'), ('ST', 'STEEL'), ('FA', 'FAIRY')], max_length=30)),
                ('hp', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('name_fr', models.CharField(default='', max_length=30)),
                ('name_ar', models.CharField(default='', max_length=30)),
                ('name_jp', models.CharField(default='', max_length=30)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
